# Generated by Django 6.1 on 2026-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('element', models.CharField(choices=[('FIRE', 'Fire'), ('WATER', 'Water'), ('EARTH', 'Earth'), ('AIR', 'Air'), ('NEUTRAL', 'Neutral'), ('LEGENDARY', 'Legendary')], max_length=20)),
                ('classification', models.CharField(blank=True, max_length=50)),
                ('era_location', models.CharField(blank=True, max_length=100)),
                ('lp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('accuracy', models.PositiveIntegerField()),
                ('evasion_speed', models.PositiveIntegerField()),
                ('crit_rate', models.PositiveIntegerField()),
                ('sprite', models.ImageField(blank=True, null=True, upload_to='creatures/')),
            ],
        ),
    ]
