# Generated by Django 6.1 on 2026-08-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('element', models.CharField(choices=[('FIRE', 'Fire'), ('WATER', 'Water'), ('EARTH', 'Earth'), ('AIR', 'Air'), ('NEUTRAL', 'Neutral'), ('LEGENDARY', 'Legendary')], max_length=20)),
                ('category', models.CharField(choices=[('DAMAGE', 'Damage'), ('SUPPORT', 'Support'), ('KNOCK', 'Knock')], max_length=10)),
                ('range_class', models.CharField(choices=[('CLOSE', 'Close'), ('LONG', 'Long')], max_length=5)),
                ('skill_power', models.PositiveIntegerField()),
                ('accuracy', models.PositiveIntegerField()),
                ('fp_cost', models.PositiveIntegerField()),
                ('range_multiplier_override', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the Long-Range default multiplier for named exceptions (e.g. Apato, Brachio). Null means use the range class default', max_digits=3, null=True)),
                ('target_rule', models.CharField(choices=[('ENEMY_AZ', 'Enemy Attack Zone'), ('ENEMY_AZ_OR_SZ', 'Enemy Attack Zone or Support Zone'), ('SELF_AZ', 'Own Attack Zone')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_duration', models.PositiveIntegerField(help_text='Minimum duration, in turns.')),
                ('max_duration', models.PositiveIntegerField(help_text='Maximum duration, in turns.')),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='moveset',
            field=models.ManyToManyField(blank=True, related_name='creatures', to='battles.move'),
        ),
        migrations.AddField(
            model_name='move',
            name='status_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='battles.statuseffect'),
        ),
    ]
