# Generated by Django 6.1 on 2026-08-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_move_statuseffect_creature_moveset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(choices=[('SELF_AZ', 'Own Attack Zone'), ('ENEMY_AZ', 'Enemy Attack Zone')], max_length=10)),
                ('stat', models.CharField(choices=[('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('ACCURACY', 'Accuracy'), ('EVASION_SPEED', 'Evasion/Speed'), ('CRIT_RATE', 'Crit Rate')], max_length=20)),
                ('magnitude', models.IntegerField(help_text='Positive = buff, negative = debuff.')),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='category',
            field=models.CharField(choices=[('DAMAGE', 'Damage'), ('KNOCK', 'Knock')], max_length=10),
        ),
        migrations.AddField(
            model_name='creature',
            name='support_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatures', to='battles.supporteffect'),
        ),
    ]
