# Generated by Django 6.1 on 2026-08-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_supporteffect_alter_move_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='element',
        ),
        migrations.CreateModel(
            name='CreatureMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Skill slot order (1-4).')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.creature')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.move')),
            ],
            options={
                'ordering': ['creature', 'slot'],
                'unique_together': {('creature', 'move'), ('creature', 'slot')},
            },
        ),
        migrations.RemoveField(
            model_name='creature',
            name='moveset',
        ),
        migrations.AddField(
            model_name='creature',
            name='moveset',
            field=models.ManyToManyField(blank=True, related_name='creatures', through='battles.CreatureMove', to='battles.move'),
        ),
    ]
