# Generated by Django 6.1 on 2026-08-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_remove_move_element_creaturemove_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporteffect',
            name='name',
        ),
    ]
