# Generated by Django 6.1 on 2026-08-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_remove_supporteffect_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='support_effect',
        ),
        migrations.RemoveField(
            model_name='supporteffect',
            name='magnitude',
        ),
        migrations.RemoveField(
            model_name='supporteffect',
            name='stat',
        ),
        migrations.AddField(
            model_name='supporteffect',
            name='creature',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='support_effect', to='battles.creature'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupportEffectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('ACCURACY', 'Accuracy'), ('EVASION_SPEED', 'Evasion/Speed')], max_length=20)),
                ('magnitude', models.IntegerField(help_text='Positive = buff, negative = debuff.')),
                ('support_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_modifiers', to='battles.supporteffect')),
            ],
            options={
                'unique_together': {('support_effect', 'stat')},
            },
        ),
    ]
