# Generated by Django 6.1 on 2026-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_remove_creature_support_effect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='range_class',
        ),
        migrations.AddField(
            model_name='move',
            name='move_class',
            field=models.CharField(choices=[('ALL_AROUND', 'All-Around'), ('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('LONG_RANGE', 'Long-Range'), ('SUPPORT', 'Support'), ('TRANSFORMATION', 'Transformation')], default='ALL_AROUND', max_length=20, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='range_multiplier_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-move multiplier override. Mechanics unimplemented.', max_digits=3, null=True),
        ),
    ]
