# Generated by Django 6.1 on 2026-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_remove_move_range_class_move_move_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='status_effect',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='skill_power',
            new_name='damage',
        ),
        migrations.RemoveField(
            model_name='move',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='move',
            name='category',
        ),
        migrations.RemoveField(
            model_name='move',
            name='move_class',
        ),
        migrations.RemoveField(
            model_name='move',
            name='range_multiplier_override',
        ),
        migrations.RemoveField(
            model_name='move',
            name='target_rule',
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_class',
            field=models.CharField(choices=[('ALL_AROUND', 'All-Around'), ('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('LONG_RANGE', 'Long-Range'), ('SUPPORT', 'Support'), ('TRANSFORMATION', 'Transformation')], default='ALL_AROUND', max_length=20, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='counterable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='effect',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='StatusEffect',
        ),
    ]
