# Generated by Django 6.1 on 2026-08-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0008_remove_move_status_effect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='moveset',
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['creature', 'slot']},
        ),
        migrations.AddField(
            model_name='move',
            name='creature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moveset', to='battles.creature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='effect_success_rate',
            field=models.PositiveIntegerField(blank=True, help_text="Percent change(0-100) the effect triggers. Blank if there's no effect.", null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1, help_text='Skill slot order (1-4).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='damage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('creature', 'name'), ('creature', 'slot')},
        ),
        migrations.DeleteModel(
            name='CreatureMove',
        ),
    ]
