# Generated by Django 6.1 on 2026-08-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_remove_creature_moveset_alter_move_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.CharField(blank=True, max_length=200)),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passive_skill', to='battles.creature')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('damage', models.PositiveIntegerField(blank=True, null=True)),
                ('fp_cost', models.PositiveIntegerField()),
                ('trait_category', models.CharField(choices=[('ELEMENT', 'Element'), ('DIET', 'Diet'), ('LOCATION', 'Location'), ('ERA', 'Era')], max_length=10)),
                ('trait_value', models.CharField(help_text="This specific value required across the whole time, e.g. 'Fire' or 'Carnivor'.", max_length=100)),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_skill', to='battles.creature')),
            ],
        ),
    ]
