# Generated by Django 6.1 on 2026-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_passiveskill_teamskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='era_location',
            new_name='era',
        ),
        migrations.AddField(
            model_name='creature',
            name='diet',
            field=models.CharField(choices=[('CARNIVORE', 'Carnivore'), ('HERBIVORE', 'Herbivore')], default='CARNIVORE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='discovered_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='genus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='length_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='length_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='size_category',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamskill',
            name='trait_value',
            field=models.CharField(help_text="This specific value required across the whole time, e.g. 'Fire' or 'Carnivore'.", max_length=100),
        ),
    ]
