# Generated by Django 6.1 on 2026-08-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_rename_era_location_creature_era_creature_diet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='classification',
            new_name='group',
        ),
    ]
