# Generated by Django 6.1 on 2026-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_rename_classification_creature_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamskill',
            name='trait_value',
            field=models.CharField(help_text="This specific value required across the whole team, e.g. 'Fire' or 'Carnivore'.", max_length=100),
        ),
    ]
