# Generated by Django 6.1 on 2026-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0013_alter_teamskill_trait_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='team_skill_wildcard',
            field=models.BooleanField(default=False, help_text="Compatible with every elemental Team Skill group, even ones it doesn't share."),
        ),
    ]
