# Generated by Django 6.1 on 2026-08-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0014_creature_team_skill_wildcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='diet',
            field=models.CharField(choices=[('CARNIVORE', 'Carnivore'), ('HERBIVORE', 'Herbivore'), ('OMNIVORE', 'Omnivore'), ('PISCIVORE', 'Piscivore')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creature',
            name='discovered_location',
            field=models.CharField(choices=[('ANTARCTICA', 'Antarctica'), ('ARGENTINA', 'Argentina'), ('AUSTRALIA', 'Australia'), ('BELGIUM', 'Belgium'), ('BRAZIL', 'Brazil'), ('CANADA', 'Canada'), ('CHINA', 'China'), ('EGYPT', 'Egypt'), ('ENGLAND', 'England'), ('FRANCE', 'France'), ('GERMANY', 'Germany'), ('JAPAN', 'Japan'), ('KAZAKHSTAN', 'Kazakhstan'), ('MEXICO', 'Mexico'), ('MONGOLIA', 'Mongolia'), ('MOROCCO', 'Morocco'), ('NIGERIA', 'Nigeria'), ('PAKISTAN', 'Pakistan'), ('PORTUGAL', 'Portugal'), ('ROMANIA', 'Romania'), ('RUSSIA', 'Russia'), ('TANZANIA', 'Tanzania'), ('THAILAND', 'Thailand'), ('TURKEY', 'Turkey'), ('USA', 'U.S.A.')], max_length=15),
        ),
        migrations.AlterField(
            model_name='creature',
            name='era',
            field=models.CharField(choices=[('MESOZOIC_TRIASSIC', 'Mesozoic Triassic'), ('MESOZOIC_JURASSIC', 'Mesozoic Jurassic'), ('MESOZOIC_CRETACEOUS', 'Mesozoic Cretaceous'), ('CENOZOIC_TERTIARY', 'Cenozoic Tertiary'), ('CENOZOIC_QUATERNARY', 'Cenozoic Quaternary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='creature',
            name='size_category',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('TITANIC', 'Titanic')], max_length=10),
        ),
    ]
