# Generated by Django 6.1 on 2026-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0015_alter_creature_diet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
