# Generated by Django 6.1 on 2026-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0016_teamskillgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='number',
            field=models.PositiveSmallIntegerField(default=8, unique=True),
            preserve_default=False,
        ),
    ]
