# Generated by Django 6.1 on 2026-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0017_creature_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='dig_site',
            field=models.CharField(choices=[('BB_BASE', 'BB Base'), ('BOTTOMSUP_BAY', 'Bottomsup Bay'), ('COLDFEET_GLACIER', 'Coldfeet Glacier'), ('EXCHANGED_FOR_DP', 'Exchanged for DP'), ('GREENHORN_PLAINS', 'Greenhorn Plains'), ('KNOTWOOD_FOREST', 'Knotwood Forest'), ('MEDAL_DEALER_JOE', 'Medal-Dealer Joe'), ('MOLES_SECRET_TUNNEL', "Moles' Secret Tunnel"), ('MT_LAVAFLOW', 'Mt. Lavaflow'), ('PARCHMENT_DESERT', 'Parchment Desert'), ('PAY_TO_DIG_SITE', 'Pay-to-Dig Site'), ('RIVET_RAVINE', 'Rivet Ravine'), ('SECRET_ISLAND', 'Secret Island')], default='MT_LAVAFLOW', max_length=25),
            preserve_default=False,
        ),
    ]
