# Generated by Django 6.1 on 2026-08-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0018_creature_dig_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='status_resistance',
            field=models.PositiveIntegerField(default=0, help_text='Percent chance to resist an incoming status effect.'),
            preserve_default=False,
        ),
    ]
