# Generated by Django 6.1 on 2026-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0019_creature_status_resistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='sz_damage_multiplier',
            field=models.FloatField(default=50, help_text="Multiplier applied to this creature's Attack while in a Support Zone."),
            preserve_default=False,
        ),
    ]
