# Generated by Django 6.1 on 2026-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0020_creature_sz_damage_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='team_skill_wildcard',
        ),
        migrations.AddField(
            model_name='creature',
            name='team_skill_groups',
            field=models.ManyToManyField(blank=True, related_name='creatures', to='battles.teamskillgroup'),
        ),
    ]
