# Generated by Django 6.1 on 2026-08-29 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0021_remove_creature_team_skill_wildcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamskill',
            name='trait_category',
        ),
        migrations.RemoveField(
            model_name='teamskill',
            name='trait_value',
        ),
        migrations.AddField(
            model_name='teamskill',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_skills', to='battles.teamskillgroup'),
            preserve_default=False,
        ),
    ]
