# Generated by Django 6.1 on 2026-08-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0022_remove_teamskill_trait_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='creature',
            name='discovered_location',
        ),
        migrations.AddField(
            model_name='creature',
            name='discovered_locations',
            field=models.ManyToManyField(blank=True, related_name='creatures', to='battles.discoveredlocation'),
        ),
    ]
