# Generated by Django 6.1 on 2026-08-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0023_discoveredlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='group',
        ),
    ]
