# Generated by Django 6.1 on 2026-08-29 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0024_remove_creature_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='team_skill_group',
            field=models.ForeignKey(blank=True, help_text='Set only for a Team Skill. Blank for a regular skill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_skill_moves', to='battles.teamskillgroup'),
        ),
        migrations.AlterField(
            model_name='move',
            name='slot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Skill slot order (1-4). Blank for a Team Skill.', null=True),
        ),
        migrations.DeleteModel(
            name='TeamSkill',
        ),
    ]
