# Generated by Django 6.1 on 2026-08-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0025_move_team_skill_group_alter_move_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='team_skill_group',
        ),
        migrations.AddField(
            model_name='move',
            name='is_team_skill',
            field=models.BooleanField(default=False, verbose_name='Team Skill'),
        ),
    ]
