# Generated by Django 6.1 on 2026-08-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0026_remove_move_team_skill_group_move_is_team_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporteffect',
            name='accuracy_magnitude',
            field=models.IntegerField(blank=True, help_text='Positive = Buff, negative = debuff. Blank = unaffected.', null=True),
        ),
        migrations.AddField(
            model_name='supporteffect',
            name='attack_magnitude',
            field=models.IntegerField(blank=True, help_text='Positive = Buff, negative = debuff. Blank = unaffected.', null=True),
        ),
        migrations.AddField(
            model_name='supporteffect',
            name='defense_magnitude',
            field=models.IntegerField(blank=True, help_text='Positive = Buff, negative = debuff. Blank = unaffected.', null=True),
        ),
        migrations.AddField(
            model_name='supporteffect',
            name='evasion_speed_magnitude',
            field=models.IntegerField(blank=True, help_text='Positive = Buff, negative = debuff. Blank = unaffected.', null=True),
        ),
        migrations.DeleteModel(
            name='SupportEffectStat',
        ),
    ]
