# Generated by Django 6.1 on 2026-08-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0027_supporteffect_accuracy_magnitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='length_ft',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='length_m',
        ),
    ]
