# Generated by Django 6.1 on 2026-08-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0028_remove_creature_length_ft_remove_creature_length_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='diet',
            field=models.CharField(blank=True, choices=[('CARNIVORE', 'Carnivore'), ('HERBIVORE', 'Herbivore'), ('OMNIVORE', 'Omnivore'), ('PISCIVORE', 'Piscivore')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creature',
            name='dig_site',
            field=models.CharField(blank=True, choices=[('BB_BASE', 'BB Base'), ('BOTTOMSUP_BAY', 'Bottomsup Bay'), ('COLDFEET_GLACIER', 'Coldfeet Glacier'), ('EXCHANGED_FOR_DP', 'Exchanged for DP'), ('GREENHORN_PLAINS', 'Greenhorn Plains'), ('KNOTWOOD_FOREST', 'Knotwood Forest'), ('MEDAL_DEALER_JOE', 'Medal-Dealer Joe'), ('MOLES_SECRET_TUNNEL', "Moles' Secret Tunnel"), ('MT_LAVAFLOW', 'Mt. Lavaflow'), ('PARCHMENT_DESERT', 'Parchment Desert'), ('PAY_TO_DIG_SITE', 'Pay-to-Dig Site'), ('RIVET_RAVINE', 'Rivet Ravine'), ('SECRET_ISLAND', 'Secret Island')], max_length=25),
        ),
        migrations.AlterField(
            model_name='creature',
            name='era',
            field=models.CharField(blank=True, choices=[('MESOZOIC_TRIASSIC', 'Mesozoic Triassic'), ('MESOZOIC_JURASSIC', 'Mesozoic Jurassic'), ('MESOZOIC_CRETACEOUS', 'Mesozoic Cretaceous'), ('CENOZOIC_TERTIARY', 'Cenozoic Tertiary'), ('CENOZOIC_QUATERNARY', 'Cenozoic Quaternary')], max_length=30),
        ),
    ]
