# Generated by Django 6.1 on 2026-08-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0029_alter_creature_diet_alter_creature_dig_site_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(condition=models.Q(('is_team_skill', True)), fields=('creature',), name='unique_team_skill_per_creature'),
        ),
    ]
