# Generated by Django 6.1 on 2026-09-02 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0031_playerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTIVE', 'Active'), ('RESERVE', 'Reserve')], max_length=8)),
                ('order', models.PositiveIntegerField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slots', to='battles.creature')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='battles.team')),
            ],
            options={
                'ordering': ['team', 'role', 'order'],
                'constraints': [models.UniqueConstraint(fields=('team', 'creature'), name='unique_creature_per_team'), models.UniqueConstraint(fields=('team', 'role', 'order'), name='unique_slot_order_per_team_role')],
            },
        ),
    ]
