# Generated by Django 6.1 on 2026-09-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0033_battleroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ez_turns_left', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guest_ez_turns_left', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='battles.battleroom')),
            ],
        ),
        migrations.CreateModel(
            name='BattleCreatureState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('HOST', 'Host'), ('GUEST', 'Guest')], max_length=5)),
                ('zone', models.CharField(choices=[('AZ', 'Attack Zone'), ('SZ1', 'Support Zone One'), ('SZ2', 'Support Zone Two'), ('EZ', 'Escape Zone')], max_length=20)),
                ('current_lp', models.PositiveIntegerField()),
                ('current_fp', models.PositiveIntegerField()),
                ('status_effect', models.CharField(blank=True, max_length=100)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.creature')),
                ('battle_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creature_states', to='battles.battlestate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('battle_state', 'side', 'zone'), name='unique_zone_per_side')],
            },
        ),
    ]
