# Generated by Django 6.1 on 2026-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0034_battlestate_battlecreaturestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='passiveskill',
            name='accuracy_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='attack_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='defense_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='evasion_speed_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='lp_recovery_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='name',
            field=models.CharField(choices=[('AUTO_COUNTER', 'Auto Counter'), ('AUTO_LP_RECOVERY', 'Auto LP Recovery'), ('FP_PLUS', 'FP Plus'), ('PARTING_BLOW', 'Parting Blow'), ('ZERO_SUPPORT', 'Zero Support')], max_length=20),
        ),
    ]
