# Generated by Django 6.1 on 2026-09-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0035_passiveskill_accuracy_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('POISON', 'Poison'), ('SUPER_POISON', 'Super Poison'), ('VENOM', 'Venom'), ('SLEEP', 'Sleep'), ('SUPER_SLEEP', 'Super Sleep'), ('SCARE', 'Scare'), ('SUPER_SCARE', 'Super Scare'), ('EXCITE', 'Excite'), ('SUPER_EXCITE', 'Super Excite'), ('CONFUSE', 'Confuse'), ('SUPER_CONFUSE', 'Super Confuse'), ('ENRAGE', 'Enrage'), ('SUPER_ENRAGE', 'Super Enrage'), ('ENFLAME', 'Enflame'), ('SUPER_ENFLAME', 'Super Enflame'), ('HARDEN', 'Harden'), ('SUPER_HARDEN', 'Super Harden'), ('QUICKEN', 'Quicken'), ('SUPER_QUICKEN', 'Super Quicken'), ('COUNTER', 'Counter'), ('SUPER_COUNTER', 'Super Counter')], max_length=20, unique=True)),
                ('is_positive', models.BooleanField()),
                ('duration_turns', models.PositiveSmallIntegerField()),
                ('lp_damage_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('skills_disabled', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attack_points', models.IntegerField(blank=True, null=True)),
                ('defense_points', models.IntegerField(blank=True, null=True)),
                ('accuracy_points', models.IntegerField(blank=True, null=True)),
                ('evasion_speed_percent', models.IntegerField(blank=True, null=True)),
                ('counter_reflect_percent', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='battlecreaturestate',
            name='status_effect',
        ),
        migrations.AddField(
            model_name='battlecreaturestate',
            name='status_turns_remaining',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='status_immune',
            field=models.BooleanField(default=False, help_text='Immune to all status effects except Confuse/Super Confuse. Currently only Dinomaton.'),
        ),
        migrations.AddField(
            model_name='battlecreaturestate',
            name='active_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='battles.statuseffect'),
        ),
        migrations.AddField(
            model_name='move',
            name='inflicts_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflicting_moves', to='battles.statuseffect'),
        ),
    ]
