# Generated by Django 6.1 on 2026-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0036_statuseffect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='move',
            name='effect_success_rate',
        ),
        migrations.AddField(
            model_name='move',
            name='is_link_skill',
            field=models.BooleanField(default=False, verbose_name='Link Skill'),
        ),
        migrations.AddField(
            model_name='move',
            name='link_chance_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Percent chance (0-100) this Link activates when the AZ ally attacks. Blank unless is_link_skill=True.', null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='max_hits',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AddField(
            model_name='move',
            name='secondary_effect',
            field=models.CharField(blank=True, choices=[('ATTACK_AZ_AND_SZ', 'Attack AZ and SZ'), ('SWAP_ZONES', 'Swap Zones'), ('TRANSFORMS', 'Transforms'), ('ELIMINATE_ALL_EFFECTS', 'Eliminate All Effects'), ('EQUALIZE_FP', 'Equalize FP'), ('RECOVER_ALL_ALLIES_LP', "Recover All Allies' LP"), ('RECOVER_ONE_ALLY_LP', "Recover One Ally's LP"), ('GIVE_LP_TO_ALLIES', 'Give LP to Allies'), ('KNOCK_TO_EZ', 'Knock to EZ'), ('LOSE_LP_FOR_DAMAGE', 'Lose LP for Damage'), ('STEAL_FP', 'Steal FP'), ('STEAL_LP_EQUAL_TO_DAMAGE', 'Steal LP Equal to Damage'), ('RECOVER_LP_USING_ALLY_LP', 'Recover LP Using Ally LP')], max_length=30),
        ),
        migrations.AddField(
            model_name='move',
            name='secondary_effect_magnitude',
            field=models.PositiveIntegerField(blank=True, help_text='The {n} value for secondary effects that need one. Blank otherwise.', null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='secondary_effect_success_rate',
            field=models.PositiveIntegerField(blank=True, help_text="Percent chance (0-100) secondary_effect triggers. Blank if there's no secondary effect.", null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='status_success_rate',
            field=models.PositiveIntegerField(blank=True, help_text="Percent change(0-100) the inflicts_status triggers. Blank if there's no effect.", null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='transforms_into',
            field=models.ManyToManyField(blank=True, help_text='Only used when secondary_effect=TRANSFORMS. One entry = fixed transform; multiple = random pool.', related_name='transform_source', to='battles.move'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(condition=models.Q(('is_link_skill', True)), fields=('creature',), name='unique_link_skill_per_creature'),
        ),
    ]
