# Generated by Django 6.1 on 2026-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0037_remove_move_effect_remove_move_effect_success_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='transforms_into',
        ),
        migrations.AddField(
            model_name='move',
            name='transforms_into',
            field=models.ManyToManyField(blank=True, help_text="Only used when secondary_effect=TRANSFORMS, and only valid on a Transformation-Class creature's move. One entry = fixed transformation; multiple = random pool.", related_name='transform_source', to='battles.creature'),
        ),
    ]
