# Generated by Django 6.1 on 2026-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0038_remove_move_transforms_into_move_transforms_into'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlecreaturestate',
            name='current_fp',
        ),
        migrations.AddField(
            model_name='battlestate',
            name='guest_fp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlestate',
            name='host_fp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='fp_plus_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
