# Generated by Django 6.1 on 2026-09-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0039_remove_battlecreaturestate_current_fp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passiveskill',
            name='effect',
        ),
    ]
