# Generated by Django 6.1 on 2026-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0040_remove_passiveskill_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='slot',
            field=models.PositiveSmallIntegerField(help_text="Display order across all of this creature's moves (regular, Team and Link Skills). No effect in battle."),
        ),
    ]
