# Generated by Django 6.1 on 2026-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0041_alter_move_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlestate',
            name='active_side',
            field=models.CharField(blank=True, choices=[('HOST', 'Host'), ('GUEST', 'Guest')], max_length=5, null=True),
        ),
    ]
