# Generated by Django 6.1 on 2026-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0042_battlestate_active_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecreaturestate',
            name='has_acted',
            field=models.BooleanField(default=False),
        ),
    ]
